language: CSharp
mono:
    - latest
install:
    - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
    - dnvm upgrade
    - dnu restore
env:
    - DNX_BUILD_VERSION=$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER 
script:
    - dnu build src/SharpEqualsTester/
    - dnu build test/SharpEqualsTester.Tests
    - dnx --project test/SharpEqualsTester.Tests test